#request
bool enable 
---
#reponse
bool result 
uint8 device_index # When the error code is related to camera or gimbal device,
# it will tell you which device it is.
HMSPushInfo[] err_list # error code list in each pushing
uint32 time_stamp 